# Generated by Django 4.2.2 on 2023-07-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_sample_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
