# Generated by Django 4.2.2 on 2023-07-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
