# Generated by Django 4.2.2 on 2023-07-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_task_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-07-10'),
            preserve_default=False,
        ),
    ]
